=== ColinHewlett/theclinic/src/test/resources/SystemDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://colinhewlettsolutions.com"
           xmlns="http://colinhewlettsolutions.com"
           elementFormDefault="qualified"
		   >

    <!-- defines the root element 'sections' which contains at least one 'section' element -->
	<xs:element name="sections">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="section" type="sectionType" maxOccurs="unbounded"/> <!-- note default value 'minOccurs' attribute is 1 -->
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- 'section' element must contain one or more 'project' elements -->
	<xs:complexType name="sectionType">
		<xs:sequence>
			<xs:element name="project" type="projectType" maxOccurs="unbounded"/> <!-- note default value 'minOccurs' attribute is 1 -->
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	
	<!-- 'project' element can contain zero or more 'key' elements -->
	<xs:complexType name="projectType">
		<xs:sequence>
			<xs:element name="key" type="keyType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	
	<!-- 'key' element' must contain a single 'value' element -->
	<xs:complexType name="keyType">
		<xs:sequence>
			<xs:element name="value" type="valueType"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>

	<!-- 'value' element must contain a single data type chosen from a list of different data types -->
	<xs:complexType name="valueType">
		<xs:choice>
			
			<xs:element name="color" type="colorType"/>
			<xs:element name="dimension" type="dimensionType"/>
			<xs:element name="font" type="fontType"/>
			<xs:element name="integer" type="xs:integer"/>
			<xs:element name="point" type="pointType"/>
			<xs:element name="string" type="xs:string"/>
			<xs:element name="string_array" type="stringArrayType"/>
		</xs:choice>
	</xs:complexType>

	<!-- colorType contains a 'red', 'green' and 'blue' elements of type integer -->
    <xs:complexType name="colorType">
        <xs:sequence>
            <xs:element name="red" type="xs:integer"/>
            <xs:element name="green" type="xs:integer"/>
			<xs:element name="blue" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <!-- dimensionType contains a 'width' and 'height' element -->
    <xs:complexType name="dimensionType">
        <xs:sequence>
            <xs:element name="width" type="xs:int"/>
            <xs:element name="height" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
	
	<!-- fontType contains a String 'title', Integer 'style' and Integer 'size' elements -->
    <xs:complexType name="fontType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="style" type="xs:integer"/>
			<xs:element name="size" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <!-- pointType contains an 'x' and 'y' element -->
    <xs:complexType name="pointType">
        <xs:sequence>
            <xs:element name="x" type="xs:int"/>
            <xs:element name="y" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

	<!-- stringArrayType contains at least one 'string> element -->
    <xs:complexType name="stringArrayType">
        <xs:sequence>
            <xs:element name="string" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ColinHewlett/theclinic/src/test/resources/SystemDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<sections xmlns="http://colinhewlettsolutions.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:schemaLocation="http://colinhewlettsolutions.com SystemDefinition.xsd">	  
	
	<section id="SystemDefinition">
		<project id="UNIVERSAL">
			<key id="DEBUG">
				<value>
					<string>Disabled</string>
				</value>
			</key>
			<key id="DESKTOP_BACKGROUND">
				<value>
					<color>
						<red>0</red>
						<green>0</green>
						<blue>0</blue>
					</color>
				</value>
			</key>
			<key id="DESKTOP_ICON">
				<value>
					<string>fractal.jpg</string>
				</value>
			</key>
			<key id="LOOK_AND_FEEL">
				<value>
					<string>Metal</string>
				</value>
			</key>
			<key id="TITLED_BORDER_COLOR" >
				<value>
					<color>
						<red>0</red>
						<green>0</green>
						<blue>153</blue>
					</color>
				</value>
			</key>
			<key id="TITLED_BORDER_FONT" >
				<value>
					<font>
						<title>Segue UI</title>
						<style>1</style>
						<size>12</size>
					</font>
				</value>
			</key>
		</project>
		<project id="Fractals">
			<key id="DEPTH">
				<value>
					<integer>1</integer>
				</value>
			</key>
			
			<key id="FRACTAL_IMAGE_DIMENSION">
				<value>
					<dimension>
						<width>1000</width>
						<height>1000</height>
					</dimension>
				</value>
			</key>
			<key id="FRACTAL_IMAGE_ORIGIN">
				<value>
					<point>
						<x>100</x>
						<y>900</y>
					</point>
				</value>
			</key>
			<key id="TRIANGLE_SIDE">
				<value>
					<integer>800</integer>
				</value>
			</key>	
		</project>
		<project id="PMS" >
			<key id="DIARY_BOOKABLE_SLOT_COLOR" >
				<value>
					<color>
						<red>240</red>
						<green>240</green>
						<blue>240</blue>
					</color>
				</value>
			</key>
			<key id="DIARY_BOOKING_FIRST_ROW_COLOR" >
				<value>
					<color>
						<red>245</red>
						<green>247</green>
						<blue>208</blue>
					</color>
				</value>
			</key>
			<key id="DIARY_BOOKING_REMAINING_ROWS_COLOR" >
				<value>
					<color>
						<red>245</red>
						<green>227</green>
						<blue>167</blue>
					</color>
				</value>
			</key>
			<key id="LIST_BOOKABLE_SLOT_TEXT_COLOR_REQUEST" >
				<value>
					<color>
						<red>0</red>
						<green>0</green>
						<blue>255</blue>
					</color>
				</value>
			</key>
			<key id="LIST_EMERGENCY_BOOKING_TEXT_COLOR" >
				<value>
					<color>
						<red>255</red>
						<green>0</green>
						<blue>0</blue>
					</color>
				</value>
			</key>
			<key id="LIST_UNBOOKABLE_SLOT_TEXT_COLOR_REQUEST" >
				<value>
					<color>
						<red>0</red>
						<green>0</green>
						<blue>255</blue>
					</color>
				</value>
			</key>
			<key id="MASTER_DOCUMENT">
				<value>
					<string>C:\Users\colin\OneDrive\Documents\pms\master_documents\MasterRecallEmail.docx</string>
				</value>
			</key>
			<key id="PRINT_FOLDER">
				<value>
					<string>c:\pms\printouts\</string>
				</value>
			</key>
			<key id="SMTP_MESSAGE">
				<value>
					<string>c:\user\colin\recall_message\recall.docx</string>
				</value>
			</key>
			<key id="SMTP_SERVER_IN">
				<value>
					<string>pop.iomartcloud.com</string>
				</value>
			</key>
			<key id="SMTP_SERVER_IN_PORT">
				<value>
					<integer>110</integer>
				</value>
			</key>
			<key id="SMTP_SERVER_OUT">
				<value>
					<string>smtp.iomartcloud.com</string>
				</value>
			</key>
			<key id="SMTP_SERVER_OUT_PORT">
				<value>
					<integer>547</integer>
				</value>
			</key>
			<key id="SMTP_USER">
				<value>
					<string>admin.theclinic@jeffamos.co.uk</string>
				</value>
			</key>
		    <key id="STORE_ACCESS_URL">
				<value>
					<string>jdbc:ucanaccess://c:/pms/repository/86.accdb</string>
				</value>
			</key>
			<key id="STORE_POSTGRES_URL">
				<value>
					<string>jdbc:postgressql://localhost:5432/pms_test</string>
				</value>
			</key>
			<key id="STORE_TYPE">
				<value>
					<string>ACCESS</string>
				</value>
			</key>
			<key id="USERS">
				<value>
					<string_array>
						<string>beverley</string>
						<string>rosie</string>
						<string>jeff</string>
						<string>janine</string>
						<string>colin</string>
					</string_array>
				</value>
			</key>
		</project>
	</section>
</sections>
